# Generated by Django 5.2.7 on 2025-10-16 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('registration_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255, unique=True)),
                ('aircraft_type', models.CharField(choices=[('Commercial', 'Commercial Aircraft'), ('Private', 'Private Aircraft'), ('Military', 'Military Aircraft'), ('Cargo', 'Cargo Aircraft')], default='Private', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='aircrafts/')),
                ('manufacturing_date', models.DateField(auto_now_add=True)),
                ('fuel_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_speed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)])),
                ('satus', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance'), ('Storage', 'Storage'), ('Retired', 'Retired'), ('Other', 'Other')], default='Active', max_length=255)),
            ],
        ),
    ]
