# Generated by Django 5.2.8 on 2025-11-05 14:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('satart_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('icao_code', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
            ],
            options={
                'db_table': 'certification',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('RAD', 'Radio'), ('DAT', 'Data Link'), ('SAT', 'Satellite')], max_length=3)),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('message_content', models.TextField()),
                ('flight_phase', models.CharField(choices=[('TAX', 'Taxi'), ('TOF', 'Takeoff'), ('CRU', 'Cruise'), ('LAN', 'Landing')], max_length=3)),
                ('altitude', models.PositiveIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('frequency', models.DecimalField(decimal_places=2, max_digits=6)),
                ('signal_strength', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestamp', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('PIL', 'Pilot'), ('COP', 'Co-Pilot'), ('ENG', 'Engineer'), ('ATT', 'Flight Attendant'), ('MT', 'Maintenance Technician'), ('SP', 'Security Personnel'), ('OTHER', 'Other')], max_length=10)),
                ('hire_date', models.DateField()),
                ('total_flight_hours', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('unavailability_dates', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True)),
                ('departure_airport', models.CharField(max_length=10)),
                ('arrival_airport', models.CharField(max_length=10)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_km', models.PositiveIntegerField()),
                ('altitude_max', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('SCHED', 'Scheduled'), ('BOARD', 'Boarding'), ('INFLT', 'In Flight'), ('DELAY', 'Delayed'), ('CANC', 'Cancelled'), ('ARRVD', 'Arrived')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PIL', 'Pilot'), ('COP', 'Co-Pilot'), ('ENG', 'Engineer'), ('ATT', 'Flight Attendant'), ('MT', 'Maintenance Technician'), ('SP', 'Security Personnel'), ('OTHER', 'Other')], max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flight_crew_member',
                'ordering': ['flight', 'crew_member'],
            },
        ),
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_time', models.DateTimeField()),
                ('cruising_altitude_ft', models.PositiveIntegerField()),
                ('fuel_required_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('JET', 'Jet A-1'), ('AVG', 'Avgas'), ('DSL', 'Diesel')], default='JET', max_length=3)),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier', models.CharField(max_length=100)),
                ('refueled_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('MIN', 'Minor'), ('MAJ', 'Major'), ('CRI', 'Critical')], max_length=3)),
                ('occurred_at', models.DateTimeField()),
                ('location_description', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('corrective_action', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INPR', 'In Progress'), ('COMP', 'Completed'), ('DEFR', 'Deferred')], default='OPEN', max_length=4)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', max_length=4)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('ENG', 'Engine'), ('AVN', 'Avionics'), ('AIR', 'Airframe'), ('ELE', 'Electrical'), ('INT', 'Interior'), ('OTH', 'Other')], default='OTH', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ENG', 'Engine'), ('AVN', 'Avionics'), ('AIR', 'Airframe'), ('ELE', 'Electrical'), ('INT', 'Interior'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PartInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_on', models.DateTimeField()),
                ('removed_on', models.DateTimeField(blank=True, null=True)),
                ('hours_used', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.PositiveIntegerField()),
                ('is_international', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('GPS', 'GPS'), ('ALT', 'Alimeter'), ('SPD', 'Speedometer')], max_length=3)),
                ('anufacturer', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('CAL', 'Calibrated'), ('ERR', 'Error')], max_length=3)),
                ('last_calibration', models.DateTimeField(blank=True, null=True)),
                ('next_calibration', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wind_speed_kt', models.DecimalField(decimal_places=1, max_digits=5)),
                ('visibility_km', models.DecimalField(decimal_places=1, max_digits=4)),
                ('metar', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['name', '-model'], 'verbose_name': 'Aircraft', 'verbose_name_plural': 'Aircrafts'},
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(choices=[('Commercial', 'Commercial Aircraft'), ('Private', 'Private Aircraft'), ('Military', 'Military Aircraft'), ('Cargo', 'Cargo Aircraft'), ('Other', 'Other')], default='Private', max_length=255),
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['name', 'model'], name='aircraft_name_6ea524_idx'),
        ),
        migrations.AlterModelTable(
            name='aircraft',
            table='aircraft',
        ),
        migrations.AddField(
            model_name='aircraftcommunication',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_aircraft', to='aircraft_app.aircraft'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['name'], name='certificati_name_9a1b2d_idx'),
        ),
        migrations.AddField(
            model_name='communication',
            name='aircraft_communications',
            field=models.ManyToManyField(through='aircraft_app.AircraftCommunication', through_fields=('communication', 'aircraft'), to='aircraft_app.aircraft'),
        ),
        migrations.AddField(
            model_name='aircraftcommunication',
            name='communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_history', to='aircraft_app.communication'),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='active_certifications',
            field=models.ManyToManyField(blank=True, related_name='crew_member_active_certifications', to='aircraft_app.certification'),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='crew_member_certifications', to='aircraft_app.certification'),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crew_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft_flights', to='aircraft_app.aircraft'),
        ),
        migrations.AddField(
            model_name='flightcrewmember',
            name='crew_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='aircraft_app.crewmember'),
        ),
        migrations.AddField(
            model_name='flightcrewmember',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='aircraft_app.flight'),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='alternate_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_for', to='aircraft_app.airport'),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='flight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='aircraft_app.flight'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='aircraft_app.aircraft'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='aircraft_app.aircraft'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='aircraft_app.flight'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='aircraft_app.crewmember'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='aircraft_app.aircraft'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='performed_by',
            field=models.ManyToManyField(blank=True, related_name='maintenance_performed', to='aircraft_app.crewmember'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='work_orders', to='aircraft_app.maintenancetask'),
        ),
        migrations.AddField(
            model_name='partinstallation',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_installations', to='aircraft_app.aircraft'),
        ),
        migrations.AddField(
            model_name='partinstallation',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='aircraft_app.part'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_destination', to='aircraft_app.airport'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_originating', to='aircraft_app.airport'),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_plans', to='aircraft_app.route'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aircraft_app.aircraft'),
        ),
        migrations.AddField(
            model_name='weatherreport',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_reports', to='aircraft_app.airport'),
        ),
        migrations.AddIndex(
            model_name='flightcrewmember',
            index=models.Index(fields=['flight', 'crew_member'], name='flight_crew_flight__8c3bb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flightcrewmember',
            unique_together={('flight', 'crew_member')},
        ),
    ]
