# Generated by Django 5.2.8 on 2025-11-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='manufacturing_date',
            field=models.DateField(auto_now=True),
        ),
    ]
