# Generated by Django 5.2.8 on 2025-11-13 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_app', '0002_airport_certification_maintenancetask_part_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['registration_number'], 'verbose_name': 'Aircraft', 'verbose_name_plural': 'Aircrafts'},
        ),
        migrations.AlterModelOptions(
            name='aircraftcommunication',
            options={'ordering': ['-satart_date_time'], 'verbose_name': 'Aircraft Communication', 'verbose_name_plural': 'Aircraft Communications'},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['iata_code'], 'verbose_name': 'Airport', 'verbose_name_plural': 'Airports'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['name'], 'verbose_name': 'Certification', 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='communication',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Communication', 'verbose_name_plural': 'Communications'},
        ),
        migrations.AlterModelOptions(
            name='crewmember',
            options={'ordering': ['employee_id'], 'verbose_name': 'Crew Member', 'verbose_name_plural': 'Crew Members'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-departure_time'], 'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
        migrations.AlterModelOptions(
            name='flightplan',
            options={'ordering': ['-filed_time'], 'verbose_name': 'Flight Plan', 'verbose_name_plural': 'Flight Plans'},
        ),
        migrations.AlterModelOptions(
            name='fuellog',
            options={'ordering': ['-refueled_at'], 'verbose_name': 'Fuel Log', 'verbose_name_plural': 'Fuel Logs'},
        ),
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'Incident Report', 'verbose_name_plural': 'Incident Reports'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-opened_at'], 'verbose_name': 'Maintenance Record', 'verbose_name_plural': 'Maintenance Records'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'ordering': ['code'], 'verbose_name': 'Maintenance Task', 'verbose_name_plural': 'Maintenance Tasks'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['part_number'], 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterModelOptions(
            name='partinstallation',
            options={'ordering': ['-installed_on'], 'verbose_name': 'Part Installation', 'verbose_name_plural': 'Part Installations'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['origin', 'destination'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['serial_number'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
        migrations.AlterModelOptions(
            name='weatherreport',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Weather Report', 'verbose_name_plural': 'Weather Reports'},
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['registration_number'], name='aircraft_registr_929eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraftcommunication',
            index=models.Index(fields=['aircraft', 'communication'], name='aircraft_co_aircraf_7561a4_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraftcommunication',
            index=models.Index(fields=['satart_date_time'], name='aircraft_co_satart__059911_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['iata_code'], name='airport_iata_co_45ca75_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['icao_code'], name='airport_icao_co_7dcb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['city', 'country'], name='airport_city_f53e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['name'], name='certificati_name_9a1b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['valid_until'], name='certificati_valid_u_5d3d05_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['timestamp'], name='communicati_timesta_5670a5_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['communication_type'], name='communicati_communi_fbb5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='crewmember',
            index=models.Index(fields=['employee_id'], name='crew_member_employe_be1450_idx'),
        ),
        migrations.AddIndex(
            model_name='crewmember',
            index=models.Index(fields=['role'], name='crew_member_role_0acd14_idx'),
        ),
        migrations.AddIndex(
            model_name='crewmember',
            index=models.Index(fields=['is_active'], name='crew_member_is_acti_7d6a62_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['flight_number'], name='flight_flight__eba58d_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_time'], name='flight_departu_e5be02_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['aircraft'], name='flight_aircraf_cf474a_idx'),
        ),
        migrations.AddIndex(
            model_name='flightplan',
            index=models.Index(fields=['flight'], name='flight_plan_flight__9d8c57_idx'),
        ),
        migrations.AddIndex(
            model_name='flightplan',
            index=models.Index(fields=['filed_time'], name='flight_plan_filed_t_5c2c06_idx'),
        ),
        migrations.AddIndex(
            model_name='fuellog',
            index=models.Index(fields=['aircraft', 'refueled_at'], name='fuel_log_aircraf_0ac71c_idx'),
        ),
        migrations.AddIndex(
            model_name='fuellog',
            index=models.Index(fields=['refueled_at'], name='fuel_log_refuele_90707a_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['occurred_at'], name='incident_re_occurre_db4bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['severity'], name='incident_re_severit_a2608c_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['flight', 'aircraft'], name='incident_re_flight__d95eca_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['work_order_number'], name='maintenance_work_or_910278_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['aircraft', 'status'], name='maintenance_aircraf_e14920_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['status', 'priority'], name='maintenance_status_c3986a_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['code'], name='maintenance_code_a25239_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['category'], name='maintenance_categor_3bce16_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['part_number'], name='part_part_nu_8044de_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category'], name='part_categor_d46169_idx'),
        ),
        migrations.AddIndex(
            model_name='partinstallation',
            index=models.Index(fields=['aircraft', 'part'], name='part_instal_aircraf_e47038_idx'),
        ),
        migrations.AddIndex(
            model_name='partinstallation',
            index=models.Index(fields=['installed_on'], name='part_instal_install_1d3c66_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin', 'destination'], name='route_origin__b41d45_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_international'], name='route_is_inte_71b883_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['serial_number'], name='sensor_serial__a31421_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['aircraft'], name='sensor_aircraf_9bf58c_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherreport',
            index=models.Index(fields=['airport', 'timestamp'], name='weather_rep_airport_7d7a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherreport',
            index=models.Index(fields=['timestamp'], name='weather_rep_timesta_5fb5a2_idx'),
        ),
        migrations.AlterModelTable(
            name='aircraft',
            table='aircraft',
        ),
        migrations.AlterModelTable(
            name='aircraftcommunication',
            table='aircraft_communication',
        ),
        migrations.AlterModelTable(
            name='airport',
            table='airport',
        ),
        migrations.AlterModelTable(
            name='certification',
            table='certification',
        ),
        migrations.AlterModelTable(
            name='communication',
            table='communication',
        ),
        migrations.AlterModelTable(
            name='crewmember',
            table='crew_member',
        ),
        migrations.AlterModelTable(
            name='flight',
            table='flight',
        ),
        migrations.AlterModelTable(
            name='flightplan',
            table='flight_plan',
        ),
        migrations.AlterModelTable(
            name='fuellog',
            table='fuel_log',
        ),
        migrations.AlterModelTable(
            name='incidentreport',
            table='incident_report',
        ),
        migrations.AlterModelTable(
            name='maintenancerecord',
            table='maintenance_record',
        ),
        migrations.AlterModelTable(
            name='maintenancetask',
            table='maintenance_task',
        ),
        migrations.AlterModelTable(
            name='part',
            table='part',
        ),
        migrations.AlterModelTable(
            name='partinstallation',
            table='part_installation',
        ),
        migrations.AlterModelTable(
            name='route',
            table='route',
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='sensor',
        ),
        migrations.AlterModelTable(
            name='weatherreport',
            table='weather_report',
        ),
    ]
