# Generated by Django 5.2.8 on 2025-11-27 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_app', '0002_alter_aircraft_manufacturing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='manufacturing_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 27, 8, 19, 59, 714143, tzinfo=datetime.timezone.utc)),
        ),
    ]
