# Generated by Django 5.2.8 on 2025-11-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft_app', '0002_aircraftcommunication_airport_certification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftcommunication',
            options={'ordering': ['-satart_date_time'], 'verbose_name': 'Aircraft Communication', 'verbose_name_plural': 'Aircraft Communications'},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['iata_code'], 'verbose_name': 'Airport', 'verbose_name_plural': 'Airports'},
        ),
        migrations.AlterModelOptions(
            name='communication',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Communication', 'verbose_name_plural': 'Communications'},
        ),
        migrations.AlterModelOptions(
            name='crewmember',
            options={'ordering': ['employee_id'], 'verbose_name': 'Crew Member', 'verbose_name_plural': 'Crew Members'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['flight_number'], 'verbose_name': 'Flight', 'verbose_name_plural': 'Flights'},
        ),
        migrations.AlterModelOptions(
            name='flightplan',
            options={'ordering': ['flight'], 'verbose_name': 'Flight Plan', 'verbose_name_plural': 'Flight Plans'},
        ),
        migrations.AlterModelOptions(
            name='fuellog',
            options={'ordering': ['-refueled_at'], 'verbose_name': 'Fuel Log', 'verbose_name_plural': 'Fuel Logs'},
        ),
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'Incident Report', 'verbose_name_plural': 'Incident Reports'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-opened_at'], 'verbose_name': 'Maintenance Record', 'verbose_name_plural': 'Maintenance Records'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'ordering': ['code'], 'verbose_name': 'Maintenance Task', 'verbose_name_plural': 'Maintenance Tasks'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['part_number'], 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterModelOptions(
            name='partinstallation',
            options={'ordering': ['-installed_on'], 'verbose_name': 'Part Installation', 'verbose_name_plural': 'Part Installations'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['origin', 'destination'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['name'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
        migrations.AlterModelOptions(
            name='weatherreport',
            options={'ordering': ['airport', '-timestamp'], 'verbose_name': 'Weather Report', 'verbose_name_plural': 'Weather Reports'},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('origin', 'destination')},
        ),
        migrations.AlterModelTable(
            name='aircraftcommunication',
            table='aircraft_communication',
        ),
        migrations.AlterModelTable(
            name='airport',
            table='airport',
        ),
        migrations.AlterModelTable(
            name='communication',
            table='communication',
        ),
        migrations.AlterModelTable(
            name='crewmember',
            table='crew_member',
        ),
        migrations.AlterModelTable(
            name='flight',
            table='flight',
        ),
        migrations.AlterModelTable(
            name='flightplan',
            table='flight_plan',
        ),
        migrations.AlterModelTable(
            name='fuellog',
            table='fuel_log',
        ),
        migrations.AlterModelTable(
            name='incidentreport',
            table='incident_report',
        ),
        migrations.AlterModelTable(
            name='maintenancerecord',
            table='maintenance_record',
        ),
        migrations.AlterModelTable(
            name='maintenancetask',
            table='maintenance_task',
        ),
        migrations.AlterModelTable(
            name='part',
            table='part',
        ),
        migrations.AlterModelTable(
            name='partinstallation',
            table='part_installation',
        ),
        migrations.AlterModelTable(
            name='route',
            table='route',
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='sensor',
        ),
        migrations.AlterModelTable(
            name='weatherreport',
            table='weather_report',
        ),
    ]
